### ISSUE TITLE
Register for Push Notifications always fails

### ISSUE THREAD

**Issue by pejakm** [bbindreiter/PushNotificationTester_App#1]
I have compiled latest master, and "Register for Push Notifications" at step 1. always fails. What did I do wrong? I'm using microG framework, which actually works, but it seems this app refuses to cooperate. I had no problems with previous versions. Also, I did not test the official app from PlayStore (I have no ways of downloading it since I don't have Playstore on my phone).

**Comment by pejakm** [comment]
I managed to find the v1.5 apk somewhere, and it works on my current configuration. So I must be doing something wrong when compiling.

**Comment by bbindreiter** [comment]
Did you setup the server part?

**Comment by pejakm** [comment]
I didn't know about that, sorry. Anyway, it's too complicated for me to setup the server part. Thanks.
