### ISSUE TITLE
Fails to Register for Push Notifications

### ISSUE THREAD

**Issue by ghost** [bbindreiter/PushNotificationTester_App#3]
some details [here](https://github.com/microg/android_packages_apps_GmsCore/issues/353)
With a newer version of Play Services, or more specifically, microG GmsCore, the app fails to register for push notifications. The app displays no other information other than that the "Register for Push Notifications" check fails while the other three checks succeed. Other apps, such as Skype and Signal Private Messenger, register just fine.
It _has_ been over six months before the app was updated, perhaps something changed that this app hasn't accounted for yet?

**Comment by bbindreiter** [comment]
Very likely yes. The production version in Google Play is using an outdated version (9.3) of the play-services library. I'll update everything to the latest and push an update to Play. Thanks for the hint, appreciate it.

**Comment by ghost** [comment]
I got the update and tried again and it worked; thanks for the fix!
