### ISSUE TITLE
This is the Chinese language

### ISSUE THREAD

**Issue by AcAugus** [bbindreiter/PushNotificationTester_App#4]
Hope to add it，I really appreciate it.
[strings.xml.txt](https://github.com/bbindreiter/PushNotificationTester_App/files/1025110/strings.xml.txt)

**Comment by bbindreiter** [comment]
thank you for your contribution. can you open up a pull request? btw, only those keys need to be translated: https://github.com/bbindreiter/PushNotificationTester_App/blob/master/app/src/main/res/values/strings.xml
